---
author: "Nombre Completo Autor"
date: "27/10/2017"
documentclass: book
forprint: true  # true: imprime a dos caras, false: libro digital
fontsize: 12pt # 10pt,11pt
geometry: margin = 2.5cm 
bibliography: ["bib/library.bib", "bib/paquetes.bib"]
# metodobib -> true: natbib (descomentar: citation_package: natbib) 
#           -> false: pandoc (comentar: citation_package: natbib)
metodobib: true
#natbib: plainnat, abbrvnat, unsrtnat
biblio-style: "plainnat"
#Método 2 (pandoc): descomente una línea de las 2 siguientes en caso de usarlo
csl: methods-in-ecology-and-evolution.csl      # no numera mejor en las citas
#csl: acm-sig-proceedings-long-author-list.csl  # numera peor en las citas
link-citations: yes
output: 
  pdf_document:
    keep_tex: no
    number_sections: yes
    citation_package: natbib  # comentado usa: pandoc-citeproc
    #toc: yes
    fig_caption: yes
    template: latex/templateMemoriaTFE.tex
    includes:
      #before_body: portadas/latex_paginatitulo_modTFE.tex
      #in_header: latex/latex_preambulo.tex
      #after_body: latex/latex_antes_enddoc.tex
---



```{r include=FALSE}
knitr::opts_chunk$set(fig.path = 'figurasR/',
                      echo = FALSE, warning = FALSE, message = FALSE,
                      fig.pos="H",fig.align="center",out.width="95%",
                      cache=FALSE)
```


<!-- \setcounter{chapter}{2} -->
<!-- \setcounter{chapter}{2} escribir 2 para capítulo 3  -->
<!-- \pagenumbering{arabic} -->

\ifdefined\ifprincipal
\else
\setlength{\parindent}{1em}
\pagestyle{fancy}
\setcounter{tocdepth}{4}
\tableofcontents
<!-- \nocite{*} -->
\fi

\ifdefined\ifdoblecara
\fancyhead{}{}
\fancyhead[LE,RO]{\scriptsize\rightmark}
\fancyfoot[LO,RE]{\scriptsize\slshape \leftmark}
\fancyfoot[C]{}
\fancyfoot[LE,RO]{\footnotesize\thepage}
\else
\fancyhead{}{}
\fancyhead[RO]{\scriptsize\rightmark}
\fancyfoot[LO]{\scriptsize\slshape \leftmark}
\fancyfoot[C]{}
\fancyfoot[RO]{\footnotesize\thepage}
\fi
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0.4pt}


# Introducción

## Objetivos

Rev-El objetivo del presente trabajo será analizar los distintos sistemas de votación que existen en la actualidad que puedan ser aplicados actualmente en España, aplicar estos sistemas a España, indicando sus ventajas e inconvenientes y proponer nuevos sistemas de votación o reparto para una eventual reforma de la Ley Orgánica del Régimen Electoral.

## ¿Qué significa votar?

### Origen

Según la Real Academia de la Lengua Española votar proviene de la palabra latina votare (hacer votos, hacer ofrendas religiosas), es un verbo formado a partir del latín votum, originalmente una ofrenda religiosa o promesa a los dioses con objeto de lograr algo deseado, que luego pasaría a significar un deseo expreso. Tiempo después pasó al terreno político, en latín propiamente el voto político se denomina suffragium. Votum es un nombre a partir del verbo vovere ( hacer un exvoto u ofrenda religiosa). De este verbo latino se derivan tambien votivo, exvoto, devoto y devoción.

### Significado

En su primera acepcion en el diccionario de la Real Academia de la Lengua Española define votar como: "Dicho de una persona: Dar su voto o decir su dictamen en una reunión o cuerpo deliberante, o en una elección de personas." 

Para terminar de definir mejor el término buscamos la definición en el diccionario del español jurídico, en el cual en la primera acepcion nos resulta útil para la delimitación del término que queremos definir, en su primera acepción lo define como: "Dicho de una persona: Dar su voto o decir su dictamen en una reunión o cuerpo deliberante, o en una elección de personas." 

### ¿Votación o sufragio?

Las dos palabras son sinónimas, aunque en la segunda acepción de la palabra sufragio según la Real Academia de la lengua: "Sistema electoral para la provisión de cargos" nos referimos más al voto como sistema, y en el voto se entiende más como referencia a la persona que realiza el acto de votar.
A lo largo del trabajo trataremos indistintamente ambos términos.


## Sistema electoral en España

### Orígenes 

El origen de el sistema electoral español se remonta a principios del siglo XIX, en una España invadida por el ejército de Napoleón. El vacío de poder facilitó la convocatoria de una asamblea nacional, las cortes, en la ciudad de Cádiz con diputados venidos de todas las regiones tanto de la península como de ultramar. La asamblea concluyó con la promulgación de la constitución de 1812.

En la instruccion de 1810 comienzan a a parecer los mecanismos para elegir a los representantes tanto parroquiales, de partido y de provincia. La fórmula electoral escogida fué la mayoritaria. El sufragio es masculino universal e indirecto, aunque se requería que los electores ejerciesen algún tipo de industria.
Ya en la constitución de 1812 se reguló todo el proceso electoral en los artículos 27 a 103, se determinó una distrubución de 1 diputado por cada 70.000 personas.

Formalmente las leyes que regulan el derecho de sufragio se remontan a 1837, estableciéndose en el año 1869 el sufragio universal consolidado en 1907 por ley.

### Sistema electoral de la constitución de 1978

El sistema actual español se rige bajo tres normas, en primer lugar la misma constitución de 1978, y mas tarde la Ley Orgánica del Régimen Electoral Central 5/1985, de 19 de Junio, en donde se regula las elecciones al Parlamento Europeo, al Congreso y Senado y las elecciones de los municipiosy la del 2/2011, del 28 de Enero en donde se modifica la anterior Ley Orgánica. 

### Descripción del sistema Electoral Español

La descripción del sistema Electoral Español se encuentra el la LOREG (Ley Orgánica del Régimen Electoral Español)
En el caso de España debemos diferenciar la elección de Diputados y Senadores, cada provincia es considerada como una circunscripción electoral. Como excepción a la regla las ciudades de Ceuta y Melilla son consideradas cada una de ellas como una circunscripción electoral.
En el artículo 161.2 se nos añade otra excepción para la elección de Senadores en donde se consideran circunscripciones las siguientes islas o agrupaciones de islas: Mallorca, Menorca, Ibiza-Formentera, Gran Canaria, Fuerteventura, Lanzarote, Tenerife, Hierro, Gomera y La Palma.

### Congreso

#### Número diputados

- El congreso está formado por un número fijo de diputados, 350.
- Cada una de las provincias les corresponden inicialmente al menos dos diputados, excepto las excepciones anteriormente anunciadas, donde Ceuta y Melilla están representadas por un diputado cada una de ellas.
- Los 248 diputados restantes se distribuyen entre las provincias proporcionalmente a su  población según el siguiente método:

    1. $\textrm{Cuota de Reparto} = \frac{248}{\text{Total de la poblaci\'{o}n de derecho de las provincias peninsulares e insulares}}$
      
      
      
    2. $\textrm{Diputados} = \text{Entero} \left\{\frac{\text{Población de derecho provincial}}{\text{Cuota de Reparto}}\right\}$
      
      
    3. Diputados Restantes = 348 - Número Diputados paso 2  
       Diputados Totales = Diputados + Restantes, uno a cada una de las provincias cuyo cociente, obtenido conforme al punto anterior, tenga una fracción decimal mayor. 

#### Reparto de Escaños

- Se aplica la llamada ley D´Hont

- No se tienen en cuenta aquellas candidaturas que no hubieran obtenido, al menos, el 3% de los votos válidos emitidos en la circunscripción.

-  Se ordenan de mayor a menor, en una columna, las cifras de votos obtenidos por las restantes candidaturas.

-  Se divide el número de votos obtenidos por cada candidatura por 1, 2, 3, etc., hasta un número igual al de escaños correspondientes a la circunscripción. Los escaños se atribuyen a las candidaturas que obtengan los cocientes mayores, atendiendo a un orden decreciente.

    +  Cuando en la relación de cocientes coincidan dos correspondientes a distintas candidaturas, el escaño se atribuirá a la que mayor número total de votos hubiese obtenido.

- Los escaños correspondientes a cada candidatura se adjudican a los candidatos incluidos en ella, por el orden de colocación en que aparezcan.

- En las circunscripciones de Ceuta y Melilla será proclamado electo el candidato que mayor número de votos hubiese obtenido.

### Senado

- En cada circunscripción provincial se eligen cuatro Senadores.

- En cada circunscripción insular se elige el siguiente número de Senadores: tres en Gran Canaria, Mallorca y Tenerife; uno en Ibiza-Formentera, Menorca, Fuerteventura, Gomera, Hierro, Lanzarote y La Palma.

- Las Poblaciones de Ceuta y Melilla eligen cada una de ellas dos Senadores.

-  Las Comunidades Autónomas designan además un Senador y otro más para cada millón de habitantes de su respectivo territorio. La designación corresponde a la Asamblea Legislativa de la Comunidad Autónoma, de acuerdo con lo que establezcan sus Estatutos, que aseguran, en todo caso, la adecuada representación proporcional. A efectos de dicha designación el número concreto de Senadores que corresponda a cada Comunidad Autónoma se determinará tomando como referencia el censo de población de derecho vigente en el momento de celebrarse las últimas elecciones generales al Senado.

- La elección directa de los Senadores en las circunscripciones provinciales, insulares y en Ceuta y Melilla se rige por lo dispuesto en los apartados siguientes:

    a) Los electores pueden dar su voto a un máximo de tres candidatos en las circunscripciones provinciales, dos en Gran Canaria, Mallorca, Tenerife, Ceuta y Melilla, y uno en las restantes circunscripciones insulares.

    b) Serán proclamados electos aquellos candidatos que obtengan mayor número de votos hasta complementar el de Senadores asignados a la circunscripción.


## Métodos de reparto de escaños

A continuación presentaremos los distintos métodos de reparto de escaños
Paquete Electoral

### Ley D´Hont

La ley D´Hont lleva el nombre del matemático y jurista belga Victor D´Hont , el cual describió la metodología en el año 1878 en su libro *"La représentation proportionnelle des partis par un électeur"*. [^3.1]

[^3.1]: Puede leerse el línea el segundo libro del autor: *"Système pratique et raisonné de représentation proportionelle"* en  http://mat.uab.cat/~xmora/bibliografia/DHondt1882.pdf

Se trata de un método de promedio mayor, utilizado para asignar los escaños usualmente en sistemas de listas. Es un sistema que trata de asignar los escaños aproximados al número de votos recibidos y que incentiva las coaliciones de partidos.  
Es el sistema más habitualmente utilizado en las democracias actuales.

#### Reparto

Una vez escrutados la totalidad de los votos, se calculan cocientes según la fórmula:  

$\textrm{Cociente} = \frac{V}{s+1}$  donde:  

$V$: Representa el número total de votos recibidos por la lista.  

$s$: Representa el número de escaños que cada lista se ha llevado de momento, inicialmente 0 para cada lista.  

El número de votos recibidos por cada lista se divide primero por 1, después por 2, 3, hasta el número total de escaños para ese distrito.




### Método Sainte-Laguë
### Método Huntington-Hill

### Cuota Hagenbach-Bischoff
### Método de cifra repartidora
### Método de Condorcet
### Método de promedios mayores
### Método del resto mayor
#### Cociente Hare
#### Cociente Droop
#### Cociente Imperiali

### Método Schulze
### Regla de Hamilton
### Representación proporcional de la lista de partidos












